### ISSUE TITLE
Can't click on top part of results page, including advancedsearch settings area

### ISSUE THREAD

**Issue by Fliptron** [bombledmonk/advancedsearch#12]
AdvancedSearch V4.3.5.3
Chrome Version 78.0.3904.70 (Official Build) (64-bit)
Windows 7 Pro x64
Did a re-install and refresh of advancedsearch but it did not change issue.

On pages that are the results overview (https://www.digikey.com/products/en?keywords=lpc4330)
clicking in the "Keyword" box anywhere except over the text does not bring focus to the box.. Marked in Blue. None of the items in the blue box to the right can be selected. Stuff in the green box can be selected as well as everything below.

![Screencapture_1](https://user-images.githubusercontent.com/5866985/67750258-1c113a80-f9ec-11e9-9cc7-b0c5a287bc39.jpg)

On the more detailed results page (https://www.digikey.com/products/en/integrated-circuits-ics/embedded-microcontrollers/685?k=lpc43)
Nothing in the blue area can be clicked.

![Screencapture_2](https://user-images.githubusercontent.com/5866985/67750282-2af7ed00-f9ec-11e9-9fdb-dcb23206b298.jpg)

Hovering over prices also doesn't work anymore. When hovering over a price, it shows a faint "Loading", then is shows a white box with rounded corners, the size of a single price, with a faint shadow, to the right of the 1 of price.  Hover over the "Find By Image" does work.

Otherwise, as always, I love this feature.

Thanks

**Comment by bombledmonk** [comment]
I've put this off for a while.  I'll see what I can do.  Thanks for the motivation.

**Comment by bombledmonk** [comment]
This did get fixed a while back. Just cleaning up the issue now.

**Comment by Fliptron** [comment]
Thanks Ben, appreciated.
