### ISSUE TITLE
What is clippy

### ISSUE THREAD

**Issue by k1mgy** [bombledmonk/advancedsearch#2]
What is this annoying clippy thing?  How do I get rid of it?

Thanks.

**Comment by bombledmonk** [comment]
It'll go away by itself tomorrow. A little leftover fun from April 1st.

**Comment by k1mgy** [comment]
Thanks!

Although minimally cute, little clippy got in my way.  I wanted to 
attack him with some wire cutters, but unable.

/m

**Comment by bombledmonk** [comment]
If you're ever feeling nostalgic.... He's only a setting away.    If he ever shows up again (which I doubt) I'll make sure he obeys a checkbox.  If I was more artistic I probably would have made him into a little LED. Or maybe a little IC package named DIPpy...  😛 
![image](https://user-images.githubusercontent.com/4141691/38954254-c9763c22-4316-11e8-9da1-809e0b700043.png)
