### ISSUE TITLE
Script fails to recognize URL in the https://www.digikey.com/number/en/MFG/Foo/Bar/JohnDoe notation.

### ISSUE THREAD

**Issue by Solamare** [bombledmonk/advancedsearch#8]
Please see https://www.digikey.com/number/en/stmicroelectronics/497/LM*58/22264 & https://www.digikey.com/number/en/microchip-technology/150/MCP6282/21931 as examples. I found this after clicking the "base part number" attribute link for some ICs.

**Comment by Solamare** [comment]
Upon further inspection the search from this type of link doesn't have parent categories or ties to the base Digi-Key search functionality. It may be out of scope for this script.

**Comment by bombledmonk** [comment]
Interesting.  May I ask how you happened upon these URLs?  Google?

**Comment by Solamare** [comment]
The hyperlink is tied to the attribute [Base Part Number | (some hyperlink)]

An example can be found at [this page](https://www.digikey.com/product-detail/en/microchip-technology/MCP6282T-E-MS/MCP6282T-E-MSTR-ND/593723)

**Comment by bombledmonk** [comment]
Ah, ok.  I'm pretty sure that's a one line fix.

**Comment by bombledmonk** [comment]
The userscript should update on its own depending on your Tampermonkey's settings.  If you'd like to update faster wait 10 or so minutes for the CDN to finish refereshing and click this like to update manually.  https://hest.pro/s/advancedmanualupdate
